### ISSUE TITLE
Ego cannot park in 

### ISSUE THREAD

**Issue by Fengtao22** [qintonguav/e2e-parking-carla#19]
Hi, thanks for open source the code. 

I have downloaded the pre-trained model last-0.75.ckpt and conducted evaluation using the default settings by running: 

> python3 carla_parking_eva.py

 However, the ego does not show any interests in parking into the target spot and the evaluation results are consistent with my visual observation:
        TSR   TFR  NTSR  NTFR    CR    OR    TR  APE  AOE  APT   AIT
Avg  0.000 0.000 0.000 0.000 0.368 0.213 0.581  NaN  NaN  NaN 0.000.

Any suggestions in implement the evaluation script? Thanks!

**Comment by Fengtao22** [comment]
The issue exists when I use Carla-0.9.15 and when I change it to 0.9.11, the ego can perform reasonably.

**Comment by jishumiao95** [comment]
I think you should collect the data via 0.9.15 then train the model if you want to conduct the experiments on it. Due to there are so many differences between 11 and 15's rgb image.
