### ISSUE TITLE
Environment installation failed

### ISSUE THREAD

**Issue by apighetti** [qintonguav/e2e-parking-carla#22]
Hi there, I tried to install your conda environment to test the pre-trained model, but upon installation I come across this error:

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - pillow==9.4.0=py37h6a678d5_0
  - libidn2==2.3.4=h5eee18b_0
  - openh264==2.1.1=h4ff587b_0
  - lz4-c==1.9.4=h6a678d5_0
  - pyparsing==3.0.9=py37h06a4308_0
  - freetype==2.12.1=h4a9f257_0
  - mkl_random==1.2.2=py37h51133e4_0
  - libcufile==1.7.1.12=0
  - libgomp==11.2.0=h1234567_1
  - numpy-base==1.21.5=py37ha15fc14_3
  - libstdcxx-ng==11.2.0=h1234567_1
  - openssl==1.1.1w=h7f8727e_0
  - setuptools==65.6.3=py37h06a4308_0
  - typing_extensions==4.3.0=py37h06a4308_0
  - matplotlib-base==3.2.2=py37hef1b27d_0
  - libwebp-base==1.2.4=h5eee18b_1
  - lerc==3.0=h295c915_0
  - libtiff==4.5.0=h6a678d5_2
  - cryptography==39.0.1=py37h9ce1e76_0
  - certifi==2022.12.7=py37h06a4308_0
  - mkl==2021.4.0=h06a4308_640
  - _openmp_mutex==5.1=1_gnu
  - ca-certificates==2023.08.22=h06a4308_0
  - libwebp==1.2.4=h11a3e52_1
  - idna==3.4=py37h06a4308_0
  - libcufft==10.7.2.124=h4fbf590_0
  - pytorch==1.13.1=py3.7_cuda11.7_cudnn8.5.0_0
  - gnutls==3.6.15=he1e5248_0
  - zlib==1.2.13=h5eee18b_0
  - sqlite==3.41.2=h5eee18b_0
  - ld_impl_linux-64==2.38=h1181459_1
  - libdeflate==1.17=h5eee18b_0
  - tornado==6.2=py37h5eee18b_0
  - gmp==6.2.1=h295c915_3
  - intel-openmp==2021.4.0=h06a4308_3561
  - requests==2.28.1=py37h06a4308_0
  - brotlipy==0.7.0=py37h27cfd23_1003
  - pip==22.3.1=py37h06a4308_0
  - lcms2==2.12=h3be6417_0
  - pytorch-cuda==11.7=h778d358_5
  - libpng==1.6.39=h5eee18b_0
  - libtasn1==4.19.0=h5eee18b_0
  - libffi==3.4.4=h6a678d5_0
  - libgcc-ng==11.2.0=h1234567_1
  - kiwisolver==1.4.4=py37h6a678d5_0
  - mkl_fft==1.3.1=py37hd3c417c_0
  - readline==8.2=h5eee18b_0
  - python==3.7.16=h7a1cb2a_0
  - cffi==1.15.1=py37h5eee18b_3
  - giflib==5.2.1=h5eee18b_3
  - nettle==3.7.3=hbbd107a_1
  - pyopenssl==23.0.0=py37h06a4308_0
  - numpy==1.21.5=py37h6c91a56_3
  - bzip2==1.0.8=h7b6447c_0
  - tk==8.6.12=h1ccaba5_0
  - ffmpeg==4.3=hf484d3e_0
  - lame==3.100=h7b6447c_0
  - icu==58.2=he6710b0_3
  - ncurses==6.4=h6a678d5_0
  - xz==5.4.2=h5eee18b_0
  - urllib3==1.26.14=py37h06a4308_0
  - zstd==1.5.5=hc292b87_0
  - mkl-service==2.4.0=py37h7f8727e_0
  - wheel==0.38.4=py37h06a4308_0
  - libunistring==0.9.10=h27cfd23_0
  - libiconv==1.16=h7f8727e_2
  - jpeg==9e=h5eee18b_1
  
  
  Is there some problem with the specified versions? Thank you in advance for your help!

**Comment by YY-Splash** [comment]
I am having the same issue, how did you solve it if I may ask?

**Comment by apighetti** [comment]
@YY-Splash I tried it on a unix based system and it worked afterwards

**Comment by YY-Splash** [comment]
You tried Linux before? Or on Windows?

**Comment by apighetti** [comment]
I was trying on Windows, then I changed to Ubuntu 22
